name:                xlibfabric
version:             0.1.0.0
github:              "nixant/xlibfabric"
license:             BSD3
author:              "Nishant Kaushik"
maintainer:          "nixantkaushik@gmail.com"
copyright:           "2020 Nishant Kaushik"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nixant/xlibfabric#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  xlibfabric-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xlibfabric

tests:
  xlibfabric-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xlibfabric
