#include <bindings.cmacros.h>

BC_INLINE3(fi_trywait, void*, void**, int, int)
BC_INLINE2(fi_wait, void*, int, int)
BC_INLINE3(fi_poll, void*, void**, int, int)
BC_INLINE3(fi_poll_add, void*, void*, uint64_t, int)
BC_INLINE3(fi_poll_del, void*, void*, uint64_t, int)
BC_INLINE4(fi_eq_open, void*, void*, void**, void*, int)
BC_INLINE5(fi_eq_read, void*, uint32_t*, void*, size_t, uint64_t, ssize_t)
BC_INLINE3(fi_eq_readerr, void*, void*, uint64_t, ssize_t)
BC_INLINE5(fi_eq_write, void*, uint32_t, const *, size_t, uint64_t, ssize_t)
BC_INLINE6(fi_eq_sread, void*, uint32_t*, void*, size_t, int, uint64_t, ssize_t)
BC_INLINE5(fi_eq_strerror, void*, int, const *, char*, size_t, const char*)
BC_INLINE3(fi_cq_read, void*, void*, size_t, ssize_t)
BC_INLINE4(fi_cq_readfrom, void*, void*, size_t, fi_addr_t*, ssize_t)
BC_INLINE3(fi_cq_readerr, void*, void*, uint64_t, ssize_t)
BC_INLINE5(fi_cq_sread, void*, void*, size_t, const *, int, ssize_t)
BC_INLINE6(fi_cq_sreadfrom, void*, void*, size_t, fi_addr_t*, const *, int, ssize_t)
BC_INLINE1(fi_cq_signal, void*, int)
BC_INLINE5(fi_cq_strerror, void*, int, const *, char*, size_t, const char*)
BC_INLINE1(fi_cntr_read, void*, uint64_t)
BC_INLINE1(fi_cntr_readerr, void*, uint64_t)
BC_INLINE2(fi_cntr_add, void*, uint64_t, int)
BC_INLINE2(fi_cntr_adderr, void*, uint64_t, int)
BC_INLINE2(fi_cntr_set, void*, uint64_t, int)
BC_INLINE2(fi_cntr_seterr, void*, uint64_t, int)
BC_INLINE3(fi_cntr_wait, void*, uint64_t, int, int)
